spring:
  application:
    name: androidApiProcess
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
  cloud:
    config:
      label:
  #autoconfigure:
   # exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #autoconfigure:
  #exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #exclude[1]: org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  security:
   user :
     name: user
     password: pass
  zipkin:
    base-url: http://localhost:9411
    enabled: false
  boot:
    admin:
      client:
        url: http://localhost:53105
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: mobileuser
    url: jdbc:mariadb://localhost:3307/mobiledb
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    password: mobile
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          use-new-id-generator-mappings: false
      show-sql: 'true'
      hibernate:
        hbm2ddl:
           auto: update
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  data:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_EMPTY
    serialization:
      write-date-keys-as-timestamps: false
      write-dates-as-timestamps: false
    time-zone: UTC
server:
  address: 0.0.0.0
  port: 55530
  compression.enabled: true
  http2.enabled: true
  error:
    include-message: always
management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  endpoint.logfile.external-file: ../logs/androidApiProcess.log
logging:
  config: classpath:log4j2-spring.yml
  file.name: androidApiProcess.log
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: method