spring:
  application:
    name: androidApiProcess
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
  cloud:
    config:
      label:
  security:
   user :
     name: user
     password: pass
#  zipkin:
#    base-url: http://localhost:9411
#    enabled: false
  boot:
    admin:
      client:
        url: http://localhost:53105
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: mobileuser
    url: jdbc:mariadb://localhost:3307/mobiledb
    testWhileIdle: 'true'
    validationQuery: SELECT 1
    password: mobile
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
          use-new-id-generator-mappings: false
      show-sql: 'true'
      hibernate:
        hbm2ddl:
           auto: update
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  data:
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: NON_EMPTY
    serialization:
      write-date-keys-as-timestamps: false
      write-dates-as-timestamps: false
    time-zone: UTC
appApi:
  credentialsMap:
  "ApkType": "E-BILLING"
  "ApkVersion": "Ver 1.2.454"
  "BluetoothID": "45:45:78:FF:V2"
  "DeviceName": "POCO M3"
  "DeviceID": "c760c7d0bf9ade1d"
  "DeviceNotificationID": "548778778779744546"
  "IMEI": "C760C7D0BF9ADE1D"
  "Latitude": "8.5517394"
  "Longitude": "8.787944"
  "Altitude": "0.0000"
  "ServiceName": "SaveOrUpdateCompanyDetails"
  "TokenID": "548778778779744546"
server:
  address: 0.0.0.0
  port: 55530
  compression.enabled: true
  http2.enabled: true
  error:
    include-message: always
management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always
  endpoint.logfile.external-file: ../logs/androidApiProcess.log
logging:
  config: classpath:log4j2-spring.yml
  file.name: androidApiProcess.log
springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: method